### ISSUE TITLE
Plugin is outdated for 2020+

### ISSUE THREAD

**Issue by jonzarecki** [andrewpeng02/gpu-monitor-plugin#2]
Hey! 

Great work on the plugin, is it possible to re-compile the plugin for 2020+ (2020.1,2020.2)? 
(Hoping this isn't too much and just works out of the box)

**Comment by andrewpeng02** [comment]
I recompiled the plugin for 2020+ and updated the plugin on the Jetbrains plugins site (v1.3.3). Let me know if there are any more issues!
